---
- name: copy ntpdate package
  copy:
    src: ntpdate-4.2.6p5-25.el7_3.2.x86_64.rpm
    dest: /tmp/ntpdate-4.2.6p5-25.el7_3.2.x86_64.rpm

- name: install ntpdate
  yum:
    name: /tmp/ntpdate-4.2.6p5-25.el7_3.2.x86_64.rpm
    state: present

- name: initial sync of time
  shell: ntpdate -u {{ openshift_ntpserver }}

- name: list rhn registration
  command: subscription-manager list
  register: sm_output

- name: register system to rhn
  command: subscription-manager register --username={{ openshift_rhel_subscription_name }} --password={{ openshift_rhel_subscription_password }}
  when: sm_output.stdout | search("Status.*Unknown")

- name: auto-attach system to rhn
  command: subscription-manager auto-attach
  when: sm_output.stdout | search("Status.*Unknown")

- name: attach system to rhn
  command: subscription-manager attach
  when: sm_output.stdout | search("Status.*Unknown")

- name: enable required rhel channels
  shell: |
    subscription-manager unsubscribe --all &&
    subscription-manager attach --pool={{ openshift_rhel_subscription_pool_id }} &&
    subscription-manager repos --disable='*' &&
    yum-config-manager --disable \* &&
    subscription-manager repos \ 
        --enable="rhel-7-server-rpms" \
        --enable="rhel-7-server-extras-rpms" \
        --enable="rhel-7-server-ose-3.11-rpms" \
        --enable="rh-gluster-3-client-for-rhel-7-server-rpms" \
        --enable="rhel-7-server-ansible-2.6-rpms"
  when: sm_output.stdout | search("Status.*Unknown")

- name: install heketi package
  yum:
    name: heketi-client
    state: present

- name: install glusterfs packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "glusterfs"
    - "glusterfs-client-xlators"
    - "glusterfs-libs"
    - "glusterfs-fuse"
