---
- name: set server hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: make sure NetworkManager is installed
  yum:
    name: NetworkManager
    state: present

- name: set openshift dns servers variable
  set_fact:
    openshift_dns_servers: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
  with_items: "{{ groups.dns }}"

- name: configure NetworkManager
  template:
    src: nm.conf.j2
    dest: /etc/NetworkManager/conf.d/nm.conf
    owner: root
    group: root
    mode: 0644
  notify: restart NetworkManager
    
- name: immediately restart NetworkManager
  meta: flush_handlers
  
- name: set timezone
  timezone:
    name: "{{ openshift_timezone }}"
