---
- name: copy ntpdate package
  copy:
    src: ntpdate-4.2.6p5-25.el7_3.2.x86_64.rpm
    dest: /tmp/ntpdate-4.2.6p5-25.el7_3.2.x86_64.rpm

- name: install ntpdate
  yum:
    name: /tmp/ntpdate-4.2.6p5-25.el7_3.2.x86_64.rpm
    state: present

- name: initial sync of time
  shell: ntpdate -u {{ ope_ntpserver }}

- name: list rhn registration
  command: subscription-manager list
  register: sm_output

- name: register system to rhn
  command: subscription-manager register --username={{ ope_rhel_subscription_name }} --password={{ ope_rhel_subscription_password }}
  when: sm_output.stdout | search("Status.*Unknown")

- name: auto-attach system to rhn
  command: subscription-manager auto-attach
  when: sm_output.stdout | search("Status.*Unknown")

- name: attach system to rhn
  command: subscription-manager attach
  when: sm_output.stdout | search("Status.*Unknown")

- name: enable required rhel channels
  shell: |
    subscription-manager unsubscribe --all &&
    subscription-manager attach --pool={{ ope_rhel_subscription_pool_id }} &&
    subscription-manager repos --disable='*' &&
    subscription-manager repos --enable='rhel-7-server-rpms' \
        --enable='rhel-7-server-extras-rpms' \
        --enable='rhel-7-server-ose-3.7-rpms' \
        --enable='rhel-7-fast-datapath-rpms' \
        --enable='rhel-7-server-optional-rpms'
  when: sm_output.stdout | search("Status.*Unknown")

- name: enable glusterfs rhel channel
  shell: |
    subscription-manager repos --enable=rh-gluster-3-for-rhel-7-server-rpms
  when: inventory_hostname in {{ groups['glusterfs'] }} or in {{ groups['glusterfs_registry'] }}
