---
- name: upgrade all packages to the latest version 
  package:
    name: "*"
    state: latest

- name: reboot the server
  command: shutdown -r now
  sudo: yes
  async: 0
  poll: 0
  ignore_errors: true

- name: waiting for server to restart
  local_action:
    module:
      wait_for:
        host: "{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}"
        port: "{{ ansible_ssh_port }}"
        delay: 15
        search_regex: OpenSSH
