---
- name: upgrade all packages to the latest version 
  package:
    name: "*"
    state: latest

- name: check if reboot is necessary
  shell: "needs-restarting  -r ; echo $?"
  register: need_restart

- name: reboot the server if necessary
  command: shutdown -r now
  async: 0
  poll: 0
  ignore_errors: true
  when: need_restart.stdout.find('Reboot is required') != -1

- name: waiting for server to restart
  wait_for:
    host: "{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}"
    port: "{{ ansible_ssh_port }}"
    delay: 15
    search_regex: OpenSSH
  vars:
    ansible_connection: local
  when: need_restart.stdout.find('Reboot is required') != -1
